// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnElFjmEnjYPCrKr1E7zrP7pyQv-RzCFA',
    appId: '1:317753511062:web:cefd3247fae141a94dc6b7',
    messagingSenderId: '317753511062',
    projectId: 'pizzeria1-79d5e',
    authDomain: 'pizzeria1-79d5e.firebaseapp.com',
    storageBucket: 'pizzeria1-79d5e.appspot.com',
    measurementId: 'G-4NW2QTG52B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAESXRn14_0EHWT_uDq90iROxOV8Ruuulo',
    appId: '1:317753511062:android:7d2b7618f89061dd4dc6b7',
    messagingSenderId: '317753511062',
    projectId: 'pizzeria1-79d5e',
    storageBucket: 'pizzeria1-79d5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw5ZimQ9rYzsvTjCGn9IKwD24E3jVk-mc',
    appId: '1:317753511062:ios:b8ffeda8c6799dc14dc6b7',
    messagingSenderId: '317753511062',
    projectId: 'pizzeria1-79d5e',
    storageBucket: 'pizzeria1-79d5e.appspot.com',
    iosBundleId: 'com.example.pizzeria1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw5ZimQ9rYzsvTjCGn9IKwD24E3jVk-mc',
    appId: '1:317753511062:ios:b8ffeda8c6799dc14dc6b7',
    messagingSenderId: '317753511062',
    projectId: 'pizzeria1-79d5e',
    storageBucket: 'pizzeria1-79d5e.appspot.com',
    iosBundleId: 'com.example.pizzeria1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnElFjmEnjYPCrKr1E7zrP7pyQv-RzCFA',
    appId: '1:317753511062:web:568741a83fac14934dc6b7',
    messagingSenderId: '317753511062',
    projectId: 'pizzeria1-79d5e',
    authDomain: 'pizzeria1-79d5e.firebaseapp.com',
    storageBucket: 'pizzeria1-79d5e.appspot.com',
    measurementId: 'G-FLGRTT96LJ',
  );
}
